<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinancialTransaction.Application\FinancialTransaction.Application.csproj" />
    <ProjectReference Include="..\FinancialTransaction.Infrastructure\FinancialTransaction.Infrastructure.csproj" />
  </ItemGroup>

</Project>
